"""
Utility script for administrating the `users` table.

Examples:
    python runuser.py rebuild
    python runuser.py rebuild --admin-password "<mot de passe>"
    python runuser.py create --username alice --email alice@example.com
"""

from __future__ import annotations

import argparse
import sys
from contextlib import closing
from getpass import getpass
from typing import Optional

from werkzeug.security import generate_password_hash

from app.config.database import get_oracle_credentials
from app.oracle_helpers import OracleError, create_connection_from_credentials


DEFAULT_ADMIN = {
    "username": "visitor",
    "email": "visitor@example.com",
    "password": "visitor123",
}


def get_connection():
    """Open a raw Oracle connection using shared configuration."""

    credentials = get_oracle_credentials()
    return create_connection_from_credentials(credentials)


def drop_users_table(connection) -> None:
    """Drop the `users` table if it already exists."""

    statement = """
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
        END;
    """
    with closing(connection.cursor()) as cursor:
        cursor.execute(statement)
    connection.commit()


def ensure_users_table(connection) -> None:
    """Create the `users` table if it does not exist yet."""

    statement = """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE users (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR2(50) NOT NULL UNIQUE,
                    email VARCHAR2(100),
                    password_hash VARCHAR2(255) NOT NULL,
                    is_active NUMBER(1) DEFAULT 1 NOT NULL,
                    last_login TIMESTAMP,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
    """
    with closing(connection.cursor()) as cursor:
        cursor.execute(statement)
    connection.commit()


def insert_user(
    connection,
    username: str,
    email: str,
    password: str,
    is_active: bool = True,
) -> None:
    """Insert a single user row with a hashed password."""

    hashed = generate_password_hash(password)
    with closing(connection.cursor()) as cursor:
        cursor.execute(
            """
            INSERT INTO users (username, email, password_hash, is_active)
            VALUES (:username, :email, :password_hash, :is_active)
            """,
            {
                "username": username,
                "email": email,
                "password_hash": hashed,
                "is_active": 1 if is_active else 0,
            },
        )
    connection.commit()


def rebuild_users_table(
    connection,
    *,
    seed_admin: bool,
    admin_username: str,
    admin_email: str,
    admin_password: str,
) -> None:
    """Drop + recreate the users table and optionally seed an admin account."""

    drop_users_table(connection)
    ensure_users_table(connection)

    if seed_admin:
        insert_user(
            connection,
            username=admin_username,
            email=admin_email,
            password=admin_password,
            is_active=True,
        )
        print("Compte administrateur créé :")
        print(f"  - utilisateur : {admin_username}")
        print(f"  - email       : {admin_email}")
        print(f"  - mot de passe: {admin_password}")
        print("Changez ce mot de passe après la première connexion.")
    else:
        print("Table `users` recréée sans compte administrateur.")


def create_user(
    connection,
    *,
    username: str,
    email: str,
    password: str,
    is_active: bool,
) -> None:
    """Create a single standard user (active by default)."""

    ensure_users_table(connection)
    insert_user(
        connection,
        username=username,
        email=email,
        password=password,
        is_active=is_active,
    )
    status = "actif" if is_active else "inactif"
    print(f"Utilisateur '{username}' créé ({status}).")


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Administration du tableau `users`.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    rebuild_parser = subparsers.add_parser(
        "rebuild",
        help="Recrée la table et insère un compte administrateur par défaut.",
    )
    rebuild_parser.add_argument(
        "--admin-username",
        default=DEFAULT_ADMIN["username"],
        help="Identifiant du compte administrateur à créer.",
    )
    rebuild_parser.add_argument(
        "--admin-email",
        default=DEFAULT_ADMIN["email"],
        help="Email du compte administrateur.",
    )
    rebuild_parser.add_argument(
        "--admin-password",
        help="Mot de passe administrateur (sinon valeur par défaut).",
    )
    rebuild_parser.add_argument(
        "--skip-admin",
        action="store_true",
        help="Ne pas insérer de compte administrateur après la recréation.",
    )

    create_parser = subparsers.add_parser(
        "create",
        help="Crée un utilisateur classique (non administrateur).",
    )
    create_parser.add_argument("--username", required=True, help="Identifiant unique.")
    create_parser.add_argument("--email", required=True, help="Adresse email.")
    create_parser.add_argument(
        "--password",
        help="Mot de passe (si omis, une invite sera affichée).",
    )
    create_parser.add_argument(
        "--inactive",
        action="store_true",
        help="Créer l'utilisateur en tant qu'inactif.",
    )

    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)

    try:
        with closing(get_connection()) as connection:
            if args.command == "rebuild":
                admin_password = args.admin_password or DEFAULT_ADMIN["password"]
                rebuild_users_table(
                    connection,
                    seed_admin=not args.skip_admin,
                    admin_username=args.admin_username,
                    admin_email=args.admin_email,
                    admin_password=admin_password,
                )
            elif args.command == "create":
                password = args.password or getpass("Mot de passe: ")
                if not password:
                    raise ValueError("Un mot de passe valide est requis.")
                create_user(
                    connection,
                    username=args.username,
                    email=args.email,
                    password=password,
                    is_active=not args.inactive,
                )
    except RuntimeError as exc:
        print(f"Erreur pilote Oracle : {exc}")
        return 1
    except OracleError as exc:
        message = str(exc)
        if "ORA-00001" in message or "unique" in message.lower():
            print("Erreur : ce nom d'utilisateur existe déjà.")
        else:
            print(f"Erreur Oracle : {exc}")
        return 1
    except ValueError as exc:
        print(exc)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
